Basic

diff --git a/src/gen_arch b/src/gen_arch
--- a/src/gen_arch
+++ b/src/gen_arch
@@ -2,33 +2,36 @@
 
 # Generate files related architecture
 
-ARCH_DIR=$1
-SRC=src
+ARCH_DIR="$1"
+ARCH_H=arch.h
+ARCH_TBL=arch.tbl
+ARCH_GENERAL_H=arch_general.h
+SRC_DIR=src
+SCNAME_C=scname.c
 SC_H2ARR=sc_h2arr
 SC_TBL2ARR=sc_tbl2arr
-MACH_ARCH_BITS_TBL=arch.tbl
 
 if (($# != 1)); then
     echo "Usage: $0 ARCH_DIR" >& 2
     exit 1
 fi
 
-if [ ! -d ${ARCH_DIR} ]; then
+if [ ! -d "${ARCH_DIR}" ]; then
     echo "Architecture directory \"${ARCH_DIR}\" not found" >& 2
     exit 1
 fi
 
-if [ ! -x ${ARCH_DIR} ]; then
+if [ ! -x "${ARCH_DIR}" ]; then
     echo "Architecture directory \"${ARCH_DIR}\" cannot be execved" >& 2
     exit 1
 fi
 
 arch="#"
 mach=$(uname -m)
-nlines=$(wc -l < ${ARCH_DIR}/${MACH_ARCH_BITS_TBL})
+nlines=$(wc -l < "${ARCH_DIR}/${ARCH_TBL}")
 
 for ((i=1; i<=nlines; i++)); do
-    items=($(sed -n "${i}p;" ${ARCH_DIR}/${MACH_ARCH_BITS_TBL}))
+    items=($(sed -n "${i}p;" "${ARCH_DIR}/${ARCH_TBL}"))
     if [ ${items[0]} == ${mach} ]; then
         arch=${items[1]}
         bits=${items[2]}
@@ -45,14 +48,14 @@ if [ ${arch} == "#" ]; then
     exit 1
 fi
 
-if [ -f ${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl ]; then
-    sc_max=$(bash ${SRC}/${SC_TBL2ARR} ${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl ${ARCH_DIR}/scname.c)
-elif [ -f ${ARCH_DIR}/sctblsrc_${arch}_${bits}.h ]; then
-    sc_max=$(bash ${SRC}/${SC_H2ARR} ${ARCH_DIR}/sctblsrc_${arch}_${bits}.h ${ARCH_DIR}/scname.c)
+if [ -f "${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl" ]; then
+    sc_max=$(bash "${SRC_DIR}/${SC_TBL2ARR}" "${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl" "${ARCH_DIR}/${SCNAME_C}")
+elif [ -f "${ARCH_DIR}/sctblsrc_${arch}_${bits}.h" ]; then
+    sc_max=$(bash "${SRC_DIR}/${SC_H2ARR}" "${ARCH_DIR}/sctblsrc_${arch}_${bits}.h" "${ARCH_DIR}/${SCNAME_C}")
 else
-    echo "Table ${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl or header ${ARCH_DIR}/sctblsrc_$ {arch}_${bits}.h not found" >& 2
+    echo "Table \"${ARCH_DIR}/sctblsrc_${arch}_${bits}.tbl\" or header \"${ARCH_DIR}/sctblsrc_${arch}_${bits}.h\" not found" >& 2
     exit 1
 fi
 
-sed "s/__LOOP_CODE__/${loop_code}/;s/__REG_TYPE__/${reg_type}/;s/__REG_RET__/${reg_ret}/;s/__REG_PC__/${reg_pc}/;s/__SC_MAX__/${sc_max}/;" ${ARCH_DIR}/arch_general.h > ${ARCH_DIR}/arch.h
+sed "s/__LOOP_CODE__/${loop_code}/;s/__REG_TYPE__/${reg_type}/;s/__REG_RET__/${reg_ret}/;s/__REG_PC__/${reg_pc}/;s/__SC_MAX__/${sc_max}/;" "${ARCH_DIR}/${ARCH_GENERAL_H}" > "${ARCH_DIR}/${ARCH_H}"
 exit 0
diff --git a/src/sc_h2arr b/src/sc_h2arr
--- a/src/sc_h2arr
+++ b/src/sc_h2arr
@@ -8,35 +8,38 @@ if (($# != 2)); then
     exit 1
 fi
 
-if [ ! -f $1 ]; then
-    echo "Header \"$1\" not found" >& 2
+HEADER="$1"
+CFILE="$2"
+
+if [ ! -f "${HEADER}" ]; then
+    echo "Header \"${HEADER}\" not found" >& 2
     exit 1
 fi
 
-if [ ! -r $1 ]; then
-    echo "Header \"$1\" cannot be read" >& 2
+if [ ! -r "${HEADER}" ]; then
+    echo "Header \"${HEADER}\" cannot be read" >& 2
     exit 1
 fi
 
-sed -n '/^\s*#\s*define\s*__NR_/{s/^\s*#\s*define\s*__NR_//g;p;};' $1 > $2.tmp
-echo "char* scname[#] = {" > $2
+sed -n '/^\s*#\s*define\s*__NR_/{s/^\s*#\s*define\s*__NR_//;p;};' "${HEADER}" > "${CFILE}.tmp"
+echo "char* scname[#] = {" > "${CFILE}"
 pwn=0
-nlines=$(wc -l < $2.tmp)
+nlines=$(wc -l < "${CFILE}.tmp")
 
 for ((i=1; i<=nlines; i++)); do
-    items=($(sed -n "${i}p;" $2.tmp))
+    items=($(sed -n "${i}p;" "${CFILE}.tmp"))
     while [ ${pwn} != ${items[1]} ]; do
-        echo -e "\t0," >> $2
+        echo -e "\t0," >> "${CFILE}"
         ((pwn++))
     done
-    echo -e "\t\"${items[0]}\"," >> $2
+    echo -e "\t\"${items[0]}\"," >> "${CFILE}"
     ((pwn++))
     if ((i == nlines)); then
-        sed -i "1s/#/${pwn}/;$((${pwn} + 1))s/,\$//;" $2
+        sed -i "1s/#/${pwn}/;$((${pwn} + 1))s/,\$//;" "${CFILE}"
     fi
 done
 
-echo "};" >> $2
-rm $2.tmp
+echo "};" >> "${CFILE}"
+rm "${CFILE}.tmp"
 echo ${pwn}
 exit 0
diff --git a/src/sc_tbl2arr b/src/sc_tbl2arr
--- a/src/sc_tbl2arr
+++ b/src/sc_tbl2arr
@@ -8,35 +8,38 @@ if (($# != 2)); then
     exit 1
 fi
 
-if [ ! -f $1 ]; then
-    echo "Table \"$1\" not found" >& 2
+TBL="$1"
+CFILE="$2"
+
+if [ ! -f "${TBL}" ]; then
+    echo "Table \"${TBL}\" not found" >& 2
     exit 1
 fi
 
-if [ ! -r $1 ]; then
-    echo "Table \"$1\" cannot be read" >& 2
+if [ ! -r "${TBL}" ]; then
+    echo "Table \"${TBL}\" cannot be read" >& 2
     exit 1
 fi
 
-sed 's/#.*//g;/^\s*$/d;' $1 > $2.tmp
-echo "char* scname[#] = {" > $2
+sed 's/#.*//;/^\s*$/d;' "${TBL}" > "${CFILE}.tmp"
+echo "char* scname[#] = {" > "${CFILE}"
 pwn=0
-nlines=$(wc -l < $2.tmp)
+nlines=$(wc -l < "${CFILE}.tmp")
 
 for ((i=1; i<=nlines; i++)); do
-    items=($(sed -n "${i}p;" $2.tmp))
+    items=($(sed -n "${i}p;" "${CFILE}.tmp"))
     while [ ${pwn} != ${items[0]} ]; do
-        echo -e "\t0," >> $2
+        echo -e "\t0," >> "${CFILE}"
         ((pwn++))
     done
-    echo -e "\t\"${items[2]}\"," >> $2
+    echo -e "\t\"${items[2]}\"," >> "${CFILE}"
     ((pwn++))
     if ((i == nlines)); then
-        sed -i "1s/#/${pwn}/;$((${pwn} + 1))s/,\$//;" $2
+        sed -i "1s/#/${pwn}/;$((${pwn} + 1))s/,\$//;" "${CFILE}"
     fi
 done
 
-echo "};" >> $2
-rm $2.tmp
+echo "};" >> "${CFILE}"
+rm "${CFILE}.tmp"
 echo ${pwn}
 exit 0
